services:
  - type: web
    name: hand-germs-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apppy:app --bind 0.0.0.0:$PORT --workers 2 --timeout 30
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production 